name: Release MIMS

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: Build plugin
        run: |
          npm install
          npm run build
  
      - name: Set up Visual Studio
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64

      - name: Build Solution
        run: |
          msbuild /p:Configuration=Release /p:Platform=x64 "${{ env.SOLUTION_PATH }}"
        env:
            SOLUTION_PATH: src/im_switch/im_switch.sln

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          $tag = "${{ github.ref }}".Replace("refs/tags/", "")
          gh release create "$tag" --title="$tag" --draft main.js manifest.json styles.css src/im_switch/x64/Release/im_switch.exe